### ISSUE TITLE
rpc:generate client error: Could not import... No mapping for...

### ISSUE THREAD

**Issue by supermuka** [dart-lang/rpc#115]
The following error occurs when the Stubs are generated. I am using Windows OS, maybe that the problem is the inveted bar on path, but I dont sure! 

This error occurs for all packages imported into file that I have `@ApiClass()`.

> D:\Users\Samuel\IdeaProjects\auge_server>pub global run rpc:generate client  -i lib\auge_api.dart -o lib\client
> Unhandled exception:
> [IsolateSpawnException: Unable to spawn isolate: Unhandled exception:
> Could not import "package:auge_model/auge_model.dart" from "file:///D:/Users/Samuel/IdeaProjects/auge_server/lib/auge_api.dart": No mapping for 'auge_model' package when resolving 'package:auge_model/auge_model.dart'.
> null, #0      Isolate.spawnUri (dart:isolate-patch/dart:isolate/isolate_patch.dart:454)
> <asynchronous suspension>
> #1      ClientApiGenerator._isolateTrampoline (http://localhost:52367/generate.dart:298)
> <asynchronous suspension>
> #2      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:282)
> #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
> #4       ClientApiGenerator.generateDiscoveryWithImports.<anonymous closure> (http://localhost:52367/generate.dart:206)
> <asynchronous suspension>
> #5       ClientApiGenerator._withServer (http://localhost:52367/generate.dart:289)
> <asynchronous suspension>
> #6       ClientApiGenerator.generateDiscoveryWithImports (http://localhost:52367/generate.dart:204)
> <asynchronous suspension>
> #7       main (http://localhost:52367/generate.dart:122)
> <asynchronous suspension>
> #8       _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
> #9       _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

**Comment by supermuka** [comment]
I removed the `global` on command line like `pub run rpc:generate client  -i lib\auge_api.dart -o lib\client` and works.
